modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="shiningrubies"
version="1.0.0"
displayName="Shining Rubies"
credits="Thanks to all Avalon Team." 
authors="Avalon Team."
description='''
Explore and find new materials to get your ultimate end-game gear.
'''