modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="shiningrubies"
version="1.0.0"
displayName="Shining Rubies"
credits="Thanks to Avalon Team and my Twitter Followers." 
authors="Avalon Team"
description='''
A Mod that aims to expand the Cave World in a vanilla way, and adds Shining Rubies.
'''